// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModels
{
    public partial class CompiledModelsContextModel
    {
        partial void Initialize()
        {
            var customer = CustomerEntityType.Create(this);

            CustomerEntityType.CreateAnnotations(customer);

            AddAnnotation("ProductVersion", "6.0.1");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
