// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace CompiledModels
{
    [DbContext(typeof(CompiledModelsContext))]
    public partial class CompiledModelsContextModel : RuntimeModel
    {
        static CompiledModelsContextModel()
        {
            var model = new CompiledModelsContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static CompiledModelsContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
